### ISSUE TITLE
Display light for only the current mahatma

### ISSUE THREAD

**Issue by Qoooo** [InvisibleShield/FFXIV-Zodiac-Glass#3]
Currently it is displaying the accumulated lights for all the mahatma in the weapon, maybe is possible to just display the current light?

**Comment by InvisibleShield** [comment]
I already changed the display like ▨ 2/12 47/79.
I will deploy this with the next release.

**Comment by InvisibleShield** [comment]
Fixed with [Release v1.3.1502.28000](https://github.com/InvisibleShield/FFXIV-Zodiac-Glass/releases/tag/v1.3.1502.28000).
